print("Как Вас зовут?")
name=input()
print("Привет,", name)
print("Как Ваша фамилия?")
surename=input()
print("Привет", surename)
print("Как Ваше отчество?")
patronymic=input()
print("Привет", patronymic)
print("")
print(name, surename, patronymic, sep="-")
